name: Check `huixiangdou.service.main` works

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittest:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Run LLM test
        run: |
          python -m pip install -r requirements.txt
          python -m huixiangdou.service.llm_server_hybrid --config_path .github/workflows/config-ci.ini  --unittest
